---
# File is synced from Kong/template-generic and will be overwritten
name: pre-commit

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4.0.0
    - name: install shfmt
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -L -s -o $GITHUB_WORKSPACE/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.1.2/shfmt_v3.1.2_linux_amd64
        chmod +x $GITHUB_WORKSPACE/bin/shfmt
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
    - name: pre-commit github auth
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git version
        git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "git@github.com:"
    - uses: pre-commit/action@v3.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        extra_args: --from-ref origin/${{ github.base_ref }} --to-ref ${{github.event.pull_request.head.sha}}
